### PR TITLE
optimize svg loading, run tsc in lint to check types, don't include extra copies of the fonts in the assets folder

### PR DESCRIPTION
**Pull request by easrng**

### CODE REVIEW

**Comment by easrng** [comment]
~~i might be stupid~~

**Comment by valadaptive** [comment]
I'm not sure which part of the code changes is the optimization. Is it the change from `Blob#arrayBuffer` to `FileReader`? The aggregation into one `<defs>` tag?

**Comment by easrng** [comment]
Just a bunch of little things, FileReader is [way faster comparatively](https://jsperf.app/zejuna) (especially in Firefox) but they're both pretty fast so it doesn't matter a ton, the fewer DOM operations helped a bit, I tried to make fewer allocations but I didn't actually test that

**Comment by valadaptive** [comment]
I changed the structure of the font loading code back to the previous one while retaining those optimizations. Can you pull that and check if it's still the same speed?

**Comment by easrng** [comment]
You should keep the isFont, it's more idiomatic typescript.

**Comment by valadaptive** [comment]
Added it back in. Is the performance still the same as in your original PR?

**Comment by easrng** [comment]
seems about 0.8s slower at loading 1029722049 start to finish (just averaged over 7 runs each (refreshed before running) cus they're kinda long lol) (... which might not actually be enough to be statistically significant)

**Comment by valadaptive** [comment]
I measured loading 1029722049 and there's a huge amount of variation on the order of seconds, seemingly due to differences in how long it takes to render the parsed SVGs. I'm probably going to merge this as-is

**Pull request merged**
